"""initil

Revision ID: 7b44b4147259
Revises: 
Create Date: 2022-11-13 22:03:32.972387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b44b4147259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('idCategory', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idCategory')
    )
    op.create_table('Cinema',
    sa.Column('idCinema', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('idCinema')
    )
    op.create_table('Hall',
    sa.Column('idHall', sa.Integer(), nullable=False),
    sa.Column('hall_number', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idHall')
    )
    op.create_table('JWTTokens',
    sa.Column('idToken', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('idToken')
    )
    op.create_table('User',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('userName', sa.String(length=45), nullable=True),
    sa.Column('firstName', sa.String(length=45), nullable=False),
    sa.Column('secondName', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('phone', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userName')
    )
    op.create_table('Film',
    sa.Column('idFilm', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=45), nullable=False),
    sa.Column('id_idCategory', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_idCategory'], ['Category.idCategory'], ),
    sa.PrimaryKeyConstraint('idFilm')
    )
    op.create_table('Schedule',
    sa.Column('idSchedule', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('id_idFilm', sa.Integer(), nullable=True),
    sa.Column('id_idHall', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_idFilm'], ['Film.idFilm'], ),
    sa.ForeignKeyConstraint(['id_idHall'], ['Hall.idHall'], ),
    sa.PrimaryKeyConstraint('idSchedule')
    )
    op.drop_table('category')
    op.drop_table('hall')
    op.drop_table('film')
    op.drop_index('email', table_name='user')
    op.drop_index('userName', table_name='user')
    op.drop_table('user')
    op.drop_table('schedule')
    op.drop_table('cinema')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema',
    sa.Column('idCinema', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('idCinema'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('schedule',
    sa.Column('idSchedule', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('id_idFilm', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_idHall', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_idFilm'], ['film.idFilm'], name='schedule_ibfk_1'),
    sa.ForeignKeyConstraint(['id_idHall'], ['hall.idHall'], name='schedule_ibfk_2'),
    sa.PrimaryKeyConstraint('idSchedule'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('idUser', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('secondName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idUser'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('userName', 'user', ['userName'], unique=False)
    op.create_index('email', 'user', ['email'], unique=False)
    op.create_table('film',
    sa.Column('idFilm', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('id_idCategory', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_idCategory'], ['category.idCategory'], name='film_ibfk_1'),
    sa.PrimaryKeyConstraint('idFilm'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hall',
    sa.Column('idHall', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hall_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idHall'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('idCategory', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idCategory'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Schedule')
    op.drop_table('Film')
    op.drop_table('User')
    op.drop_table('JWTTokens')
    op.drop_table('Hall')
    op.drop_table('Cinema')
    op.drop_table('Category')
    # ### end Alembic commands ###
